import './date-fns'
import './notify'
import './axios'
export { default as Logger } from './logger'
export { default as i18n } from './i18n/admin'
export { default as vuetify } from './vuetify'
export { default as Auth } from './auth/admin'
export { default as apolloProvider } from './apollo/admin'
